version: '3'

services:
  pg-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: web_tech_task_2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web-app:
    build: .
    depends_on:
      - pg-server
    volumes:
      - .:/app/server
    ports:
      - "8080:8080"
